name = "reedy"
version = "0.1.0"
keywords = ["math"]
defaultTargets = ["Reedy"]

[leanOptions]
pp.unicode.fun = true # pretty-prints `fun a ↦ b`
relaxedAutoImplicit = false
weak.linter.mathlibStandardSet = true
maxSynthPendingDepth = 3

[[lean_lib]]
name = "Reedy"

[[require]]
name = "mathlib"
git = "git@github.com:joelriou/mathlib4.git"
rev = "pushout-obj-obj-refactor"

